version: "3"
services:

  dev:
    build:
      context: ./docker/php-cli
    volumes:
      - ./:/app
    command: tail -f /dev/null
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
    - 1433:1433